grid:
  nx: 801
  ny: 201
  xmin: -7.5
  xmax: 0.5
  ymin: -1
  ymax: 1
  xperiodic: True
  yperiodic: True
  epsilon: 2.5

simu:
  bi_fluid: False
  fluid: 2 #(Set to zero if bifluid else either 1 or 2)
  gravity: 0.0
  dynamic_viscosity1: 1.87e-5
  dynamic_viscosity2: 0.001
  density1: 1.2
  density2: 1
  surface_tension: 0.0728
  cfl: 0.6
  penalty_factor: 1.e+8
  time_snapshots: 0.05
  time_final: 6.0
  implicit: 0 #0: explicit 1: implicit (viscous term)
  convection_scheme: 4 # 2: mittal 3: upwind 4: weno (else central difference)
  fluid_force: "exact"

obstacles_number: 1

obstacles:
  - markers_number: 201
    diameter: 1
    density: 1
    young_modulus: 1.e+3
    elasticity_modulus: 1.e+1

export_info:
  results_dirpath: "/scratch/kmaroun/fish_freq_list"








  

